spring.application.name=gpucalc
spring.main.banner-mode=off
spring.main.web-application-type=none

logging.level.root=WARN
logging.level.org.springframework=WARN
logging.level.com.edwards.gpucalc=INFO
logging.level.com.edwards.gpucalc.app.GpuCalcApplication=WARN
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level %logger{24} - %msg%n
